@startuml Erd

' entity

entity one_to_ten {
  id: integer
  --
  column_1: integer
  column_2: integer
  column_3: integer
  column_4: integer
  column_5: integer
  column_6: integer
  column_7: integer
  column_8: integer
  column_9: integer
  column_10: integer
}

' entity-relation

@enduml
